### PR TITLE
I think i've eliminated all the (welsh) - can this be merged?

### PR DESCRIPTION
**Pull request by jasonwebber-bl**

### CODE REVIEW

**Comment by anjackson** [comment]
We'd best do #22 first as the two requests may conflict.

**Comment by jasonwebber-bl** [comment]
Great, thanks.

**Comment by anjackson** [comment]
I think this set of changes has become confused by the previous modifications. I'm going to close this one, but ask you @jasonwebber-bl to try again. Is that okay?

**Comment by anjackson** [comment]
Merged and updated manually.

**Pull request merged**
